name: Update Algolia Search Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  algolia-atomic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: |
          hugo -v --gc --minify

      - name: Update Algolia Index (en)
        env:
          ALGOLIA_APP_ID: 4O2Y44OA2O
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: "index.en"
          ALGOLIA_INDEX_FILE: "./public/index.json"
        run: |
          atomic-algolia

      - name: Update Algolia Index (zh-cn)
        env:
          ALGOLIA_APP_ID: 4O2Y44OA2O
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: "index.zh-cn"
          ALGOLIA_INDEX_FILE: "./public/zh-cn/index.json"
        run: |
          atomic-algolia
