name: health-check

on:
  # workflow_dispatch 事件允许您手动触发工作流程
  workflow_dispatch: 
    # 可以进行配置手动触发后有选项进行触发
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule 事件允许您在计划的时间触发工作流程
  schedule:
    # 设置 UTC 时间每小时 3、21、39、57 自动触发，github有误差大概在 15 分钟左右触发;有需要可以自行更改此文件调整时间
    # POSIX cron 语法，只有五个域：分 时 日 月 周
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: 3/18 * * * * 

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
    - name: check index
      run: curl "https://www.890808.xyz/" | wc -l && curl "https://890808.xyz/" | wc -l

    - name: check sub
      run: curl "https://ai.890808.xyz/" | wc -l && curl "https://oner.890808.xyz/" | wc -l