name: health-check

on:
  # workflow_dispatch 事件允许您手动触发工作流程
  workflow_dispatch: 
    # 可以进行配置手动触发后有选项进行触发
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # schedule 事件允许您在计划的时间触发工作流程
  schedule:
    # 设置 UTC 时间每天 0:00 自动触发即中国 8:00，github有误差大概在 8:15 左右触发;有需要可以自行更改此文件调整时间
    # POSIX cron 语法，只有五个域：分 时 日 月 周
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron:  0 3/18 * * *  

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: check index
      run: curl "https://www.890808.xyz/" && curl "https://890808.xyz/"

    - name: check sub
      run: curl "https://ai.890808.xyz/" && curl "https://oner.890808.xyz/"